### PR TITLE
Bump Action to Node 16

### LINKED ISSUE #36: Node.js 12 actions are deprecated
```
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: marceloprado/has-changed-path@v1
```

### PR DESCRIPTION
**Pull request by kkaulen**
Update the Action to work with Node.js 16. Current Action runs on Node.js 12 and leads to deprecation warnings in workflows that use the action. 

All tests pass and i tested my fork in a private monorepo and everythink works like a charm. 

Closes #36

### CODE REVIEW

**Comment by gurudatta-carbon** [comment]
@MarceloPrado possible to merge this change ?

**Comment by MarceloPrado** [comment]
Yes! And sorry for the delay! Will merge and release a new version

**Review by MarceloPrado — APPROVED** [review]

**Comment by gurudatta-carbon** [comment]
@MarceloPrado was this published to marketplace ?
still getting same error

```
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: marceloprado/has-changed-path@v1. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
```

**Comment by MarceloPrado** [comment]
@gurudatta-carbon yes, you can see the release here: https://github.com/MarceloPrado/has-changed-path/releases/tag/v1.0.1

Did you try bumping the version number?

**Comment by gurudatta-carbon** [comment]
> Did you try bumping the version number?

shouldn't @v1 or @v1.0 should get the latest version ? 💭 

we are using @v1

**Pull request merged**
